export const MICROSERVICE_CLIENTS = {
  USERS_SERVICE: "USERS_SERVICE",
  AUTH_SERVICE: "AUTH_SERVICE",
  ACTIVITIES_SERVICE: "ACTIVITIES_SERVICE",
  JOURNALS_SERVICE: "JOURNALS_SERVICE",
  NOTIFICATIONS_SERVICE: "NOTIFICATIONS_SERVICE",
  ONTOLOGY_SERVICE: "ONTOLOGY_SERVICE",
  SCHEDULES_SERVICE: "SCHEDULES_SERVICE",
  TASKS_SERVICE: "TASKS_SERVICE",
};
