export const PROVIDER_INFO = {
  KAKAO: {
    name: "kakao",
    clientId: process.env.KAKAO_CLIENT_ID as string,
    clientSecret: process.env.KAKAO_CLIENT_SECRET as string,
    userInfoUrl: "https://kapi.kakao.com/v2/user/me",
    refreshTokenUrl: "https://kauth.kakao.com/oauth/token",
    tokenInfoUrl: "https://kapi.kakao.com/v1/user/access_token_info",
    logoutUrl: "https://kapi.kakao.com/v1/user/logout",
    unlinkUrl: "https://kapi.kakao.com/v1/user/unlink",
  },
  GOOGLE: {
    name: "google",
    clientId: process.env.GOOGLE_CLIENT_ID as string,
    clientSecret: process.env.GOOGLE_CLIENT_SECRET as string,
    userInfoUrl: "https://www.googleapis.com/oauth2/v3/userinfo",
    refreshTokenUrl: "https://oauth2.googleapis.com/token",
    tokenInfoUrl: "https://www.googleapis.com/oauth2/v3/tokeninfo",
    logoutUrl: "https://accounts.google.com/o/oauth2/revoke",
    unlinkUrl: "https://accounts.google.com/o/oauth2/revoke",
  },
  GITHUB: {
    name: "github",
    clientId: process.env.GITHUB_CLIENT_ID as string,
    clientSecret: process.env.GITHUB_CLIENT_SECRET as string,
    userInfoUrl: "https://api.github.com/user",
    refreshTokenUrl: "https://github.com/login/oauth/access_token",
    tokenInfoUrl: "https://api.github.com/user",
    logoutUrl: "https://api.github.com/user/subscriptions",
    unlinkUrl: "https://api.github.com/user/subscriptions",
  },
};
